version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: testpr_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: testpr_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - testpr_network

  # Опционально: pgAdmin для управления БД
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: testpr_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
      - testpr_network
    depends_on:
      - postgres

volumes:
  postgres_data:
  pgadmin_data:

networks:
  testpr_network:
    driver: bridge
